[env]
TERM = "xterm-256color"

[window]
padding.x = 8
padding.y = 8

opacity = 0.9
blur = true

[font]
normal.family = "TX-02"
size = 12
offset.y = 4 # size + offset.y = line height

[colors.bright]
black = "#444b6a"
blue = "#7da6ff"
cyan = "#0db9d7"
green = "#b9f27c"
magenta = "#bb9af7"
red = "#ff7a93"
white = "#acb0d0"
yellow = "#ff9e64"

[colors.normal]
black = "#32344a"
blue = "#7aa2f7"
cyan = "#449dab"
green = "#9ece6a"
magenta = "#ad8ee6"
red = "#f7768e"
white = "#787c99"
yellow = "#e0af68"

[colors.primary]
background = "#1a1b26"
foreground = "#a9b1d6"

[keyboard]
bindings= [
  {key="Key0", mods= "Control", chars= "\u001b[48;5u" },
  {key="Key1", mods= "Control", chars= "\u001b[49;5u" },
  {key="Key2", mods= "Control", chars= "\u001b[50;5u" },
  {key="Key3", mods= "Control", chars= "\u001b[51;5u" },
  {key="Key4", mods= "Control", chars= "\u001b[52;5u" },
  {key="Key5", mods= "Control", chars= "\u001b[53;5u" },
  {key="Key6", mods= "Control", chars= "\u001b[54;5u" },
  {key="Key7", mods= "Control", chars= "\u001b[55;5u" },
  {key="Key8", mods= "Control", chars= "\u001b[56;5u" },
  {key="Key9", mods= "Control", chars= "\u001b[57;5u" }
]
