model: openai/claude-3.7-sonnet-thought
openai-api-base: https://api.githubcopilot.com
edit-format: diff
weak-model: openai/claude-3.5-sonnet
editor-edit-format: diff
show-model-warnings: false
map-tokens: 2048
dark-mode: true
code-theme: github-dark
auto-commits: false
dirty-commits: false
attribute-author: true
vim: true
yes-always: true
editor: nvim
