git:
  paging:
    externalDiffCommand: difft --color=always --display=inline --syntax-highlight=on --tab-width=2
gui:
  nerdFontsVersion: "3"
  theme:
    activeBorderColor:
      - "#ff9e64"
      - "bold"
    inactiveBorderColor:
      - "#27a1b9"
    searchingActiveBorderColor:
      - "#ff9e64"
      - "bold"
    optionsTextColor:
      - "#7aa2f7"
    selectedLineBgColor:
      - "#283457"
    cherryPickedCommitFgColor:
      - "#7aa2f7"
    cherryPickedCommitBgColor:
      - "#bb9af7"
    markedBaseCommitFgColor:
      - "#7aa2f7"
    markedBaseCommitBgColor:
      - "#e0af68"
    unstagedChangesColor:
      - "#db4b4b"
    defaultFgColor:
      - "#c0caf5"
customCommands:
  - key: "C"
    description: "conventional commit"
    context: "files"
    prompts:
      - type: "menu"
        title: "Select commit type"
        key: "Type"
        options:
          - name: "feat - A new feature"
            value: "feat"
          - name: "fix - A bug fix"
            value: "fix"
          - name: "docs - Documentation only changes"
            value: "docs"
          - name: "style - Changes that do not affect the meaning of the code"
            value: "style"
          - name: "refactor - A code change that neither fixes a bug nor adds a feature"
            value: "refactor"
          - name: "perf - A code change that improves performance"
            value: "perf"
          - name: "test - Adding missing tests"
            value: "test"
          - name: "build - Changes that affect the build system"
            value: "build"
          - name: "ci - Changes to CI configuration files"
            value: "ci"
          - name: "chore - Other changes"
            value: "chore"
          - name: "revert - Reverts a previous commit"
            value: "revert"
      - type: "input"
        title: "Scope (optional)"
        key: "Scope"
        initialValue: ""
      - type: "input"
        title: "Description"
        key: "Description"
    command: 'git commit -m "{{.Form.Type}}{{if .Form.Scope}}({{.Form.Scope}}){{end}}: {{.Form.Description}}"'
