notify = ["bun", "/Users/timo/.codex/hooks/notify.ts"]
model = "gpt-5.4"
model_reasoning_effort = "xhigh"
personality = "pragmatic"
plan_mode_reasoning_effort = "xhigh"

[projects."/Users/timo/Developer/personal/dotfiles"]
trust_level = "trusted"

[projects."/Users/timo/Developer/taxfix/expert-interaction-mono"]
trust_level = "trusted"

[projects."/Users/timo/Developer/taxfix/mobile-app"]
trust_level = "trusted"

[projects."/Users/timo/Developer/taxfix/tech-platform"]
trust_level = "trusted"

[projects."/Users/timo/Developer/taxfix/aei-chatbot"]
trust_level = "trusted"

[projects."/Users/timo/Developer/taxfix/taxcore-backend"]
trust_level = "trusted"
